baseURL = "https://jillr.dev/"
languageCode = "en-us"
title = "jillr.dev"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
publishDir = "docs"
sectionPagesMenu = "main"
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable = false
